### ISSUE TITLE
Firefox 89 styles are a bit wonky

### ISSUE THREAD

**Issue by jeffeb3** [fmash16/dotfiles#1]
Hi,
Let me first say that I don't think you owe me anything :). I appreciate that you shared your config and I have been using the firefox css and the home screen for a long time (Since September 2020). It's been great.

But, in case you know how to fix this problem, or you are interested in it, I thought I should ask.

I just updated to firefox 89 and the tabs and input boxes are all a little wonky. They have a transparent background. Specifically the auto-hidden menu bar at the top, when it comes down, it has a transparent background, and combo boxes, like where you would select a month in a web form are also transparent. I've only used it for about an hour, so there may be more stuff I haven't noticed yet.

Do you have any tips for where to look or a new .css file that I should be using?

**Comment by fmash16** [comment]
Hi,
I have switched browsers, so have not triee using the updated firefox. But
for the transperancy problem, you might want to check if your theme is set
to the default "dark" theme, and not any other theme (nit even the default
one). For my css to work, it must be the dark theme.

You can find many other cool css customizations in r/firefoxcss.
https://www.reddit.com/r/FirefoxCSS

Regards
